[package]
name = "near-metrics"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4"
prometheus = { version = "0.11", default-features = false }
log = "0.4"

